package utils

import (
	"encoding/json"

	"gopkg.in/yaml.v2"
)

// ObjToYAML converts an object to YAML, first marshalling it to JSON.
//
// Typically, one would be able to use yaml.Marshal, but since the autogenerated
// gRPC/protobuf code does not include tags for YAML, the "private" XXX_ prefixed
// fields of the gRPC object are serialized out to YAML. The objects have a JSON
// tag, so by marshaling to JSON first, we can effectively use the JSON tag as
// a YAML tag as well.
func ObjToYAML(obj interface{}) ([]byte, error) {
	j, err := json.Marshal(obj)
	if err != nil {
		return nil, err
	}

	var intermediary interface{}
	if err := yaml.Unmarshal(j, &intermediary); err != nil {
		return nil, err
	}
	return yaml.Marshal(intermediary)
}
