#
# synse.yml
#
# A simple docker compose configuration to run Synse Server
# with the emulator plugin. This setup can be useful for exploring
# the CLI capabilities and behavior.
#

version: '3'
services:
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server
    ports:
      - '5000:5000'
    environment:
      SYNSE_LOGGING: debug
      SYNSE_PLUGIN_TCP: emulator-plugin:5001
    links:
      - emulator-plugin

  emulator-plugin:
    container_name: emulator-plugin
    image: vaporio/emulator-plugin
    ports:
      - '5001:5001'
    command: ['--debug']
